name: Automated Daily Commits

on:
  schedule:
    - cron: '0 0 * * *'   # Midnight UTC
    - cron: '0 8 * * *'   # 8 AM UTC
    - cron: '0 16 * * *'  # 4 PM UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Configure Git
        run: |
          git config --global user.name "sharan-dev-ae"
          git config --global user.email "sharan-dev-ae@users.noreply.github.com"

      - name: Pull latest changes
        run: git pull --rebase origin main || true

      - name: Update README.md to trigger commit
        run: |
          echo "Last update: $(date)" > last_update.txt
          git add last_update.txt
          git commit -m "Automated commit - $(date)" && git push origin main || echo "No changes to push"
